stages:
  - build
  - deploy

build_app:
  stage: build
  script:
    - echo "Node ve React kurulumu yapılıyor"
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy_placeholder:
  stage: deploy
  script:
    - echo "Sunucuya deploy edilecek (şimdilik sadece simülasyon)"
    - echo "Burada ssh ile sunucuya bağlanılıp git pull vs yapılacak"
  only:
    - main
